#!/bin/bash

rm -rf /data/carla/town01/clear/noon/cars_50_peds_200/

./simulate.py Town01 50 200

./stitch.py sides_to_cylindrical.lut sides_to_spherical.lut -s /data/carla/town01/clear/noon/cars_50_peds_200 --remake_luts
